export * from "./accelerateBoringSections";
export * from "./alternateCameraAngles";
export * from "./avoidRepetitivePatterns";
export * from "./calmEvery10to15Seconds";
export * from "./endOnStrongestScene";
export * from "./noConsecutiveSimilarClips";
export * from "./progressiveIntensity";
export * from "./slowMotionOnKeyMomentsOnly";
export * from "./syncCutsToBeat";
