import { TransitionDefinition, TransitionId } from "@/transitions/transition.types";

/**
 * Every transition the system knows about, grouped by the style family it
 * was designed for. `compatibleStyles` (not the grouping) is what actually
 * gates eligibility at selection time — a couple of transitions are shared
 * across adjacent styles (e.g. a soft `crossDissolve` also suits Cinematic),
 * but the *majority* of each style's palette is exclusive to it, which is
 * what keeps the 6 styles from converging into "the same cuts, different
 * filter".
 */

// ---------------------------------------------------------------------------
// Adventure — terrain is used as a physical mask/motivator for every cut.
// Nothing here is "just a wipe"; every transition is anchored to a real
// piece of terrain (a ridge, a cloud bank, a valley, an elevation change).
// ---------------------------------------------------------------------------
const adventureTransitions: TransitionDefinition[] = [
  {
    id: "mountainReveal",
    displayName: "Mountain Reveal",
    description: "The next shot rises from behind a mountain silhouette, as if the camera crested the ridge itself.",
    durationRange: [0.8, 1.6],
    intensity: 6,
    compatibleStyles: ["adventure"],
    bestUsedFor: ["landscape", "establishing"],
    cameraBehavior: "Camera keeps climbing through the cut — the reveal continues the drone-flyover motion.",
    visualEffectBehavior: "Silhouette mask of the peak wipes upward to unveil the next frame.",
    easing: "easeOut",
    requiresTerrainContext: true,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["terrain"],
  },
  {
    id: "terrainMask",
    displayName: "Terrain Mask",
    description: "Uses the real contour line of the terrain as a wipe mask between the two shots.",
    durationRange: [0.6, 1.2],
    intensity: 6,
    compatibleStyles: ["adventure"],
    bestUsedFor: ["landscape", "action", "establishing"],
    cameraBehavior: "Terrain-following move that keeps the horizon anchored across the cut.",
    visualEffectBehavior: "Elevation-profile-shaped mask sweeps across the frame.",
    easing: "easeInOut",
    requiresTerrainContext: true,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["terrain"],
  },
  {
    id: "cloudWipe",
    displayName: "Cloud Wipe",
    description: "A drifting cloud bank passes through frame and the next shot emerges behind it.",
    durationRange: [1.0, 1.8],
    intensity: 5,
    compatibleStyles: ["adventure"],
    bestUsedFor: ["landscape", "establishing"],
    cameraBehavior: "Slow orbit continues underneath the cloud layer.",
    visualEffectBehavior: "Soft volumetric cloud mask with light diffusion.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["terrain"],
  },
  {
    id: "elevationLift",
    displayName: "Elevation Lift",
    description: "Camera lifts vertically with the GPX elevation gain and the next shot arrives at the new altitude.",
    durationRange: [0.7, 1.4],
    intensity: 6,
    compatibleStyles: ["adventure"],
    bestUsedFor: ["landscape", "action"],
    cameraBehavior: "Elevated-chase vertical lift synced to real elevation gain.",
    visualEffectBehavior: "Vertical parallax push with light altitude haze.",
    easing: "easeOut",
    requiresTerrainContext: true,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["terrain"],
  },
  {
    id: "valleyReveal",
    displayName: "Valley Reveal",
    description: "Camera drops into a valley and the next shot opens up as the terrain falls away.",
    durationRange: [0.9, 1.6],
    intensity: 6,
    compatibleStyles: ["adventure"],
    bestUsedFor: ["landscape", "establishing"],
    cameraBehavior: "Descending terrain-following move, mirror of Elevation Lift.",
    visualEffectBehavior: "Downward mask reveal with widening depth of field.",
    easing: "easeIn",
    requiresTerrainContext: true,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["terrain"],
  },
  {
    id: "cinematicSpeedRamp",
    displayName: "Adventure Speed Ramp",
    description: "A slow-fast-slow ramp used sparingly to punctuate one dramatic viewpoint or reveal.",
    durationRange: [1.2, 2.2],
    intensity: 7,
    compatibleStyles: ["adventure"],
    bestUsedFor: ["landscape", "action"],
    cameraBehavior: "Elevated chase accelerates through the middle of the ramp, then eases out.",
    visualEffectBehavior: "Speed-curve driven motion blur, moderate not extreme.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["terrain"],
  },
  {
    id: "mapToTerrainDive",
    displayName: "Map To Terrain Dive",
    description: "Dives from a top-down GPX map straight into the real terrain footage at that point on the route.",
    durationRange: [1.0, 1.8],
    intensity: 7,
    compatibleStyles: ["adventure"],
    bestUsedFor: ["map", "establishing"],
    cameraBehavior: "Fly-over dive matching the map's camera angle into the drone-flyover shot.",
    visualEffectBehavior: "Perspective dive/zoom from orthographic map to 3D terrain.",
    easing: "easeIn",
    requiresTerrainContext: true,
    requiresBeatSync: false,
    performanceCost: "high",
    affinities: ["terrain"],
  },
  {
    id: "ridgeLineReveal",
    displayName: "Ridge Line Reveal",
    description: "The next shot is revealed by tracking along a literal ridge line silhouette.",
    durationRange: [0.8, 1.5],
    intensity: 6,
    compatibleStyles: ["adventure"],
    bestUsedFor: ["landscape", "establishing"],
    cameraBehavior: "Slow orbit around the viewpoint continues along the ridge.",
    visualEffectBehavior: "Ridge silhouette mask sweeps horizontally.",
    easing: "easeInOut",
    requiresTerrainContext: true,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["terrain"],
  },
];

// ---------------------------------------------------------------------------
// Viral — every transition exists to be short, intense and locked to a beat.
// Nothing here is allowed to breathe; the point is that you cannot look away.
// ---------------------------------------------------------------------------
const viralTransitions: TransitionDefinition[] = [
  {
    id: "flashCut",
    displayName: "Flash Cut",
    description: "A single white-flash frame slams between the two shots.",
    durationRange: [0.08, 0.2],
    intensity: 9,
    compatibleStyles: ["viral"],
    bestUsedFor: ["action", "closeUp"],
    cameraBehavior: "Snap change — no travel, pure impact.",
    visualEffectBehavior: "One or two overexposed white frames.",
    easing: "sharpSnap",
    requiresTerrainContext: false,
    requiresBeatSync: true,
    performanceCost: "low",
    affinities: ["beat"],
  },
  {
    id: "beatCut",
    displayName: "Beat Cut",
    description: "A hard cut quantized exactly to the strongest beat in the track.",
    durationRange: [0.05, 0.15],
    intensity: 8,
    compatibleStyles: ["viral", "sport"],
    bestUsedFor: ["action", "closeUp", "portrait"],
    cameraBehavior: "Snap change timed precisely to the beat grid.",
    visualEffectBehavior: "No blur — instantaneous cut for maximum punch.",
    easing: "sharpSnap",
    requiresTerrainContext: false,
    requiresBeatSync: true,
    performanceCost: "low",
    affinities: ["beat"],
  },
  {
    id: "zoomSmash",
    displayName: "Zoom Smash",
    description: "An aggressive punch-zoom slams into the next shot.",
    durationRange: [0.15, 0.35],
    intensity: 10,
    compatibleStyles: ["viral"],
    bestUsedFor: ["action", "closeUp"],
    cameraBehavior: "Fast push-in / aggressive zoom at maximum energy.",
    visualEffectBehavior: "Radial zoom blur peaking mid-transition.",
    easing: "sharpSnap",
    requiresTerrainContext: false,
    requiresBeatSync: true,
    performanceCost: "medium",
    affinities: ["beat"],
  },
  {
    id: "whipPan",
    displayName: "Whip Pan",
    description: "The camera whips sideways fast enough to fully blur the frame, hiding the cut inside the blur.",
    durationRange: [0.15, 0.3],
    intensity: 9,
    compatibleStyles: ["viral"],
    bestUsedFor: ["action", "detail"],
    cameraBehavior: "Whip-pan camera move at maximum angular speed.",
    visualEffectBehavior: "Directional motion blur streak across the whole frame.",
    easing: "sharpSnap",
    requiresTerrainContext: false,
    requiresBeatSync: true,
    performanceCost: "medium",
    affinities: ["beat"],
  },
  {
    id: "motionBlurSwipe",
    displayName: "Motion Blur Swipe",
    description: "A directional swipe of heavy motion blur wipes the next shot in.",
    durationRange: [0.12, 0.25],
    intensity: 8,
    compatibleStyles: ["viral"],
    bestUsedFor: ["action", "detail", "closeUp"],
    cameraBehavior: "Fast map-jump-style lateral snap.",
    visualEffectBehavior: "Full-frame directional blur wipe.",
    easing: "sharpSnap",
    requiresTerrainContext: false,
    requiresBeatSync: true,
    performanceCost: "low",
    affinities: ["beat"],
  },
  {
    id: "hyperSpeedRamp",
    displayName: "Hyper Speed Ramp",
    description: "An extreme, near-constant speed ramp that never lets the pacing settle.",
    durationRange: [0.3, 0.8],
    intensity: 10,
    compatibleStyles: ["viral"],
    bestUsedFor: ["action"],
    cameraBehavior: "Fast push-in accelerates continuously through the ramp.",
    visualEffectBehavior: "Heavy speed-line motion blur.",
    easing: "sharpSnap",
    requiresTerrainContext: false,
    requiresBeatSync: true,
    performanceCost: "medium",
    affinities: ["beat"],
  },
  {
    id: "glitchPulse",
    displayName: "Glitch Pulse",
    description: "A single-frame digital glitch pulse punctuates the cut.",
    durationRange: [0.06, 0.15],
    intensity: 9,
    compatibleStyles: ["viral"],
    bestUsedFor: ["action", "closeUp"],
    cameraBehavior: "Snap change, no camera travel.",
    visualEffectBehavior: "RGB-split / digital glitch flash.",
    easing: "sharpSnap",
    requiresTerrainContext: false,
    requiresBeatSync: true,
    performanceCost: "medium",
    affinities: ["beat"],
  },
  {
    id: "impactZoom",
    displayName: "Impact Zoom",
    description: "A punchy zoom-in lands exactly on the beat drop.",
    durationRange: [0.15, 0.3],
    intensity: 9,
    compatibleStyles: ["viral"],
    bestUsedFor: ["action", "closeUp"],
    cameraBehavior: "Aggressive zoom timed to the beat drop.",
    visualEffectBehavior: "Zoom blur with a subtle screen-shake kick.",
    easing: "sharpSnap",
    requiresTerrainContext: false,
    requiresBeatSync: true,
    performanceCost: "medium",
    affinities: ["beat"],
  },
  {
    id: "snapToBeat",
    displayName: "Snap To Beat",
    description: "The camera physically snaps position exactly on a detected beat.",
    durationRange: [0.05, 0.12],
    intensity: 8,
    compatibleStyles: ["viral"],
    bestUsedFor: ["action", "portrait"],
    cameraBehavior: "Snap change quantized to the beat grid.",
    visualEffectBehavior: "No blur, instantaneous, designed to feel mechanical/rhythmic.",
    easing: "sharpSnap",
    requiresTerrainContext: false,
    requiresBeatSync: true,
    performanceCost: "low",
    affinities: ["beat"],
  },
  {
    id: "textPopReveal",
    displayName: "Text Pop Reveal",
    description: "A bold overlay text pops in on the beat as the shot changes underneath it.",
    durationRange: [0.2, 0.4],
    intensity: 7,
    compatibleStyles: ["viral"],
    bestUsedFor: ["closeUp", "portrait"],
    cameraBehavior: "Quick POV snap under the overlay pop.",
    visualEffectBehavior: "Scale + opacity pop-in synced to the beat.",
    easing: "easeOutBack",
    requiresTerrainContext: false,
    requiresBeatSync: true,
    performanceCost: "low",
    affinities: ["beat"],
  },
];

// ---------------------------------------------------------------------------
// Travel — every transition keeps the eye's direction of travel continuous.
// Nothing interrupts; the camera direction from shot N motivates shot N+1.
// ---------------------------------------------------------------------------
const travelTransitions: TransitionDefinition[] = [
  {
    id: "crossDissolve",
    displayName: "Cross Dissolve",
    description: "A gentle, even dissolve between two locations.",
    durationRange: [0.8, 1.4],
    intensity: 3,
    compatibleStyles: ["travel", "cinematic"],
    bestUsedFor: ["landscape", "establishing"],
    cameraBehavior: "Smooth drone pan continues underneath the dissolve.",
    visualEffectBehavior: "Even opacity cross-fade, no masking.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "low",
    affinities: ["flow"],
  },
  {
    id: "directionMatch",
    displayName: "Direction Match",
    description: "The camera's direction of travel in shot N continues seamlessly into shot N+1.",
    durationRange: [0.6, 1.2],
    intensity: 4,
    compatibleStyles: ["travel"],
    bestUsedFor: ["landscape", "action", "establishing"],
    cameraBehavior: "Soft tracking direction is matched frame-for-frame across the cut.",
    visualEffectBehavior: "Subtle motion-matched blend, no hard mask.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["flow"],
  },
  {
    id: "horizonMatch",
    displayName: "Horizon Match",
    description: "The horizon line is kept level and aligned across the cut so the eye never jumps.",
    durationRange: [0.6, 1.1],
    intensity: 4,
    compatibleStyles: ["travel"],
    bestUsedFor: ["landscape", "establishing"],
    cameraBehavior: "Horizon-level camera lock preserved through the cut.",
    visualEffectBehavior: "Horizontal alignment blend keyed to the horizon line.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["flow"],
  },
  {
    id: "landscapeReveal",
    displayName: "Landscape Reveal",
    description: "A gentle pullback widens the frame to reveal the next landscape.",
    durationRange: [0.9, 1.6],
    intensity: 4,
    compatibleStyles: ["travel"],
    bestUsedFor: ["landscape", "establishing"],
    cameraBehavior: "Gentle pullback widening the field of view.",
    visualEffectBehavior: "Soft-edged reveal, warm light bloom.",
    easing: "easeOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "low",
    affinities: ["flow"],
  },
  {
    id: "locationMorph",
    displayName: "Location Morph",
    description: "One location softly morphs into the next via shared color/shape cues.",
    durationRange: [0.8, 1.4],
    intensity: 5,
    compatibleStyles: ["travel"],
    bestUsedFor: ["landscape", "detail"],
    cameraBehavior: "Relaxed orbit continues through the morph.",
    visualEffectBehavior: "Shape/color-matched cross-morph blend.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "high",
    affinities: ["flow"],
  },
  {
    id: "softSwipe",
    displayName: "Soft Swipe",
    description: "A slow, softly-feathered swipe wipes gently to the next shot.",
    durationRange: [0.5, 0.9],
    intensity: 4,
    compatibleStyles: ["travel"],
    bestUsedFor: ["landscape", "detail", "establishing"],
    cameraBehavior: "Soft tracking shot continues the swipe direction.",
    visualEffectBehavior: "Feathered-edge directional wipe, low contrast.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "low",
    affinities: ["flow"],
  },
  {
    id: "parallaxDrift",
    displayName: "Parallax Drift",
    description: "Foreground and background drift at different speeds as the shot changes.",
    durationRange: [0.7, 1.3],
    intensity: 4,
    compatibleStyles: ["travel"],
    bestUsedFor: ["landscape", "detail"],
    cameraBehavior: "Gentle pullback with layered parallax drift.",
    visualEffectBehavior: "Depth-based multi-layer drift blend.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["flow"],
  },
  {
    id: "mapZoomToPlace",
    displayName: "Map Zoom To Place",
    description: "A relaxed zoom from the GPX map into the real place footage.",
    durationRange: [0.9, 1.5],
    intensity: 5,
    compatibleStyles: ["travel"],
    bestUsedFor: ["map", "establishing"],
    cameraBehavior: "Map-to-landscape blend at a relaxed, unhurried pace.",
    visualEffectBehavior: "Smooth zoom + cross-fade from map to footage.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["flow"],
  },
  {
    id: "daylightBlend",
    displayName: "Daylight Blend",
    description: "Shots are blended using natural daylight tone matching so the light itself feels continuous.",
    durationRange: [0.8, 1.4],
    intensity: 3,
    compatibleStyles: ["travel"],
    bestUsedFor: ["landscape", "portrait"],
    cameraBehavior: "Horizon-level hold through the blend.",
    visualEffectBehavior: "Warm color-temperature-matched cross-fade.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "low",
    affinities: ["flow"],
  },
];

// ---------------------------------------------------------------------------
// Sport — every transition is triggered by a real action event (a corner,
// a jump, hard braking, a technical section) — never on a fixed schedule.
// ---------------------------------------------------------------------------
const sportTransitions: TransitionDefinition[] = [
  {
    id: "impactCut",
    displayName: "Impact Cut",
    description: "A hard cut timed to a physical impact moment (landing, hit, bump).",
    durationRange: [0.05, 0.15],
    intensity: 9,
    compatibleStyles: ["sport"],
    bestUsedFor: ["action"],
    cameraBehavior: "Close-action camera holds through the impact.",
    visualEffectBehavior: "Single-frame shock cut, optional screen shake.",
    easing: "sharpSnap",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "low",
    affinities: ["action"],
  },
  {
    id: "jumpCut",
    displayName: "Jump Cut",
    description: "Cuts on the apex of a jump for maximum airtime drama.",
    durationRange: [0.08, 0.2],
    intensity: 8,
    compatibleStyles: ["sport"],
    bestUsedFor: ["action"],
    cameraBehavior: "First-person or elevated chase framing the airtime.",
    visualEffectBehavior: "Clean hard cut, no blur — let the air time read clearly.",
    easing: "sharpSnap",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "low",
    affinities: ["action"],
  },
  {
    id: "velocityBlur",
    displayName: "Velocity Blur",
    description: "Motion blur scales directly with the rider/vehicle's real GPX speed.",
    durationRange: [0.15, 0.35],
    intensity: 8,
    compatibleStyles: ["sport"],
    bestUsedFor: ["action"],
    cameraBehavior: "Side tracking matched to real velocity.",
    visualEffectBehavior: "Speed-proportional directional blur.",
    easing: "sharpSnap",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["action"],
  },
  {
    id: "cornerAttack",
    displayName: "Corner Attack",
    description: "Camera whips through a sharp corner alongside the subject, cutting at the apex.",
    durationRange: [0.2, 0.4],
    intensity: 9,
    compatibleStyles: ["sport"],
    bestUsedFor: ["action"],
    cameraBehavior: "Fast corner-follow camera banking with the turn.",
    visualEffectBehavior: "Lateral G-force blur peaking at the apex.",
    easing: "sharpSnap",
    requiresTerrainContext: true,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["action"],
  },
  {
    id: "trackingSnap",
    displayName: "Tracking Snap",
    description: "A tight tracking shot snaps to the next angle the instant the subject changes direction.",
    durationRange: [0.1, 0.25],
    intensity: 7,
    compatibleStyles: ["sport"],
    bestUsedFor: ["action"],
    cameraBehavior: "Side-tracking snap-follow.",
    visualEffectBehavior: "Quick directional snap, light blur trail.",
    easing: "sharpSnap",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "low",
    affinities: ["action"],
  },
  {
    id: "accelerationRamp",
    displayName: "Acceleration Ramp",
    description: "Speed ramps up in lockstep with a detected real acceleration event.",
    durationRange: [0.4, 0.9],
    intensity: 8,
    compatibleStyles: ["sport"],
    bestUsedFor: ["action"],
    cameraBehavior: "Low chase camera surges forward with the acceleration.",
    visualEffectBehavior: "Forward speed-line blur intensifying with real acceleration data.",
    easing: "easeIn",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["action"],
  },
  {
    id: "brakeHitCut",
    displayName: "Brake Hit Cut",
    description: "A hard cut synced to a sudden deceleration/braking event.",
    durationRange: [0.06, 0.15],
    intensity: 8,
    compatibleStyles: ["sport"],
    bestUsedFor: ["action"],
    cameraBehavior: "Aggressive tilt reacting to weight transfer under braking.",
    visualEffectBehavior: "Forward-crush blur snapping to a hard stop.",
    easing: "sharpSnap",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "low",
    affinities: ["action"],
  },
  {
    id: "dirtSwipe",
    displayName: "Dirt Swipe",
    description: "Kicked-up dirt/dust/spray sweeps across frame to mask the cut on technical terrain.",
    durationRange: [0.15, 0.3],
    intensity: 8,
    compatibleStyles: ["sport"],
    bestUsedFor: ["action"],
    cameraBehavior: "Terrain-level camera catches the debris kicking up.",
    visualEffectBehavior: "Particle/dust swipe mask.",
    easing: "sharpSnap",
    requiresTerrainContext: true,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["action"],
  },
  {
    id: "shockShakeCut",
    displayName: "Shock Shake Cut",
    description: "A sharp camera-shake punctuates a rough/technical section before cutting.",
    durationRange: [0.1, 0.25],
    intensity: 9,
    compatibleStyles: ["sport"],
    bestUsedFor: ["action"],
    cameraBehavior: "Terrain-level shake reacting to rough ground.",
    visualEffectBehavior: "High-frequency shake, then hard cut.",
    easing: "sharpSnap",
    requiresTerrainContext: true,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["action"],
  },
  {
    id: "povSnap",
    displayName: "POV Snap",
    description: "Snap cut into a first-person point of view for the most intense moment of the section.",
    durationRange: [0.08, 0.2],
    intensity: 8,
    compatibleStyles: ["sport"],
    bestUsedFor: ["action", "closeUp"],
    cameraBehavior: "First-person camera takes over immediately.",
    visualEffectBehavior: "Clean snap, minimal blur, maximum immediacy.",
    easing: "sharpSnap",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "low",
    affinities: ["action"],
  },
];

// ---------------------------------------------------------------------------
// Cinematic — every transition must be motivated by story, light or
// atmosphere. Nothing fires "just because" — restraint and easing are the
// whole point; moments are allowed to breathe.
// ---------------------------------------------------------------------------
const cinematicTransitions: TransitionDefinition[] = [
  {
    id: "fadeThroughDarkness",
    displayName: "Fade Through Darkness",
    description: "The frame fades fully to black and the next shot rises out of it — a classic act break.",
    durationRange: [1.2, 2.4],
    intensity: 3,
    compatibleStyles: ["cinematic"],
    bestUsedFor: ["establishing", "portrait"],
    cameraBehavior: "Stable crane holds, letting the fade carry the emotion.",
    visualEffectBehavior: "Full fade-to-black, then fade-up.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "low",
    affinities: ["story"],
  },
  {
    id: "epicReveal",
    displayName: "Epic Reveal",
    description: "A slow, patient reveal of scale — the subject is small, the landscape is vast.",
    durationRange: [2.0, 3.5],
    intensity: 5,
    compatibleStyles: ["cinematic"],
    bestUsedFor: ["landscape", "establishing"],
    cameraBehavior: "Controlled flyover pulls back to reveal true scale.",
    visualEffectBehavior: "Slow depth-of-field rack + widening frame.",
    easing: "easeInOut",
    requiresTerrainContext: true,
    requiresBeatSync: false,
    performanceCost: "high",
    affinities: ["story"],
  },
  {
    id: "cinematicPush",
    displayName: "Cinematic Push",
    description: "A slow, deliberate push toward the subject that motivates the cut to a closer shot.",
    durationRange: [1.5, 2.8],
    intensity: 4,
    compatibleStyles: ["cinematic"],
    bestUsedFor: ["portrait", "closeUp", "detail"],
    cameraBehavior: "Slow push-in with long-lens compression.",
    visualEffectBehavior: "Subtle focus breathing during the push.",
    easing: "easeIn",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["story"],
  },
  {
    id: "orbitBlend",
    displayName: "Orbit Blend",
    description: "A slow orbit around the subject blends seamlessly into the next shot's orbit.",
    durationRange: [1.8, 3.0],
    intensity: 4,
    compatibleStyles: ["cinematic"],
    bestUsedFor: ["landscape", "portrait"],
    cameraBehavior: "Orbit-blend camera continues its arc across the cut.",
    visualEffectBehavior: "Angular-velocity-matched cross-blend.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "high",
    affinities: ["story"],
  },
  {
    id: "focusShift",
    displayName: "Focus Shift",
    description: "A rack focus pulls attention from foreground to background, motivating the cut through the blur.",
    durationRange: [1.0, 2.0],
    intensity: 3,
    compatibleStyles: ["cinematic"],
    bestUsedFor: ["detail", "portrait", "closeUp"],
    cameraBehavior: "Framed-subject hold with a rack-focus pull.",
    visualEffectBehavior: "Depth-of-field rack focus blend.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["story"],
  },
  {
    id: "slowSpeedRamp",
    displayName: "Slow Speed Ramp",
    description: "A rare, long, deliberate speed ramp reserved for a single key story beat.",
    durationRange: [2.0, 3.5],
    intensity: 4,
    compatibleStyles: ["cinematic"],
    bestUsedFor: ["action", "portrait"],
    cameraBehavior: "Stable crane eases through the ramp with long-lens compression.",
    visualEffectBehavior: "Restrained, filmic motion blur — never extreme.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["story"],
  },
  {
    id: "atmosphericFade",
    displayName: "Atmospheric Fade",
    description: "Haze, mist or dust in the air is used to dissolve one shot into the next.",
    durationRange: [1.4, 2.6],
    intensity: 3,
    compatibleStyles: ["cinematic"],
    bestUsedFor: ["landscape", "establishing"],
    cameraBehavior: "Slow reveal drifting through the atmosphere.",
    visualEffectBehavior: "Volumetric haze cross-dissolve.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["story"],
  },
  {
    id: "shadowWipe",
    displayName: "Shadow Wipe",
    description: "A moving shadow (cloud, cliff, structure) sweeps across frame and reveals the next shot.",
    durationRange: [1.0, 2.0],
    intensity: 4,
    compatibleStyles: ["cinematic"],
    bestUsedFor: ["landscape", "establishing"],
    cameraBehavior: "Controlled flyover tracks the shadow's motion.",
    visualEffectBehavior: "Soft-edged shadow mask sweep.",
    easing: "easeInOut",
    requiresTerrainContext: true,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["story"],
  },
  {
    id: "foregroundMask",
    displayName: "Foreground Mask",
    description: "A foreground element (branch, rock, ridge) passes across the lens, hiding the cut behind it.",
    durationRange: [0.8, 1.6],
    intensity: 3,
    compatibleStyles: ["cinematic"],
    bestUsedFor: ["landscape", "detail"],
    cameraBehavior: "Smooth pullback moves past the foreground element.",
    visualEffectBehavior: "Out-of-focus foreground occlusion mask.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["story"],
  },
  {
    id: "timeOfDayBlend",
    displayName: "Time Of Day Blend",
    description: "Light shifts from one time of day to another across the cut, implying the passage of time.",
    durationRange: [1.6, 2.8],
    intensity: 4,
    compatibleStyles: ["cinematic"],
    bestUsedFor: ["landscape", "establishing"],
    cameraBehavior: "Wide establishing hold lets the light do the storytelling.",
    visualEffectBehavior: "Color-temperature and exposure ramp across the blend.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["story"],
  },
];

// ---------------------------------------------------------------------------
// Luxury — every transition must read as almost invisible: light, reflection
// and soft blur do the work, never a cut you'd consciously notice.
// ---------------------------------------------------------------------------
const luxuryTransitions: TransitionDefinition[] = [
  {
    id: "silkFade",
    displayName: "Silk Fade",
    description: "An ultra-soft, silk-smooth cross-fade with no discernible midpoint.",
    durationRange: [2.0, 3.5],
    intensity: 1,
    compatibleStyles: ["luxury"],
    bestUsedFor: ["detail", "portrait", "establishing"],
    cameraBehavior: "Floating camera drifts with no directional change.",
    visualEffectBehavior: "Extremely gradual opacity blend with soft gaussian falloff.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "low",
    affinities: ["subtle"],
  },
  {
    id: "lightSweep",
    displayName: "Light Sweep",
    description: "A soft sweep of light (lens flare or rim light) crosses the frame and reveals the next shot.",
    durationRange: [1.8, 3.0],
    intensity: 2,
    compatibleStyles: ["luxury"],
    bestUsedFor: ["detail", "establishing"],
    cameraBehavior: "Premium light movement guides the sweep direction.",
    visualEffectBehavior: "Soft bloom/flare sweep mask.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["subtle"],
  },
  {
    id: "reflectionMatch",
    displayName: "Reflection Match",
    description: "A reflective surface (water, glass, polished metal) bridges the two shots.",
    durationRange: [2.0, 3.2],
    intensity: 2,
    compatibleStyles: ["luxury"],
    bestUsedFor: ["detail", "establishing"],
    cameraBehavior: "Ultra-smooth orbit follows the reflective surface.",
    visualEffectBehavior: "Mirror-matched blend through the reflection.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "high",
    affinities: ["subtle"],
  },
  {
    id: "detailToDetail",
    displayName: "Detail To Detail",
    description: "One refined product-like detail dissolves into the next, product-photography style.",
    durationRange: [2.2, 3.5],
    intensity: 2,
    compatibleStyles: ["luxury"],
    bestUsedFor: ["detail", "closeUp"],
    cameraBehavior: "Slow detail reveal with product framing.",
    visualEffectBehavior: "Macro-soft cross-dissolve.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["subtle"],
  },
  {
    id: "floatingOrbit",
    displayName: "Floating Orbit",
    description: "A weightless, near-imperceptible orbit carries the eye into the next shot.",
    durationRange: [2.5, 4.0],
    intensity: 2,
    compatibleStyles: ["luxury"],
    bestUsedFor: ["establishing", "portrait"],
    cameraBehavior: "Floating camera orbit at minimal angular speed.",
    visualEffectBehavior: "No hard mask — pure camera-motion-driven transition.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "high",
    affinities: ["subtle"],
  },
  {
    id: "softParallax",
    displayName: "Soft Parallax",
    description: "Extremely subtle parallax drift between layers dissolves into the next composition.",
    durationRange: [2.0, 3.2],
    intensity: 1,
    compatibleStyles: ["luxury"],
    bestUsedFor: ["detail", "establishing"],
    cameraBehavior: "Soft parallax camera drift, barely perceptible.",
    visualEffectBehavior: "Layered depth drift blend.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["subtle"],
  },
  {
    id: "elegantCrossfade",
    displayName: "Elegant Crossfade",
    description: "A refined, evenly-timed crossfade with premium color continuity.",
    durationRange: [1.8, 3.0],
    intensity: 1,
    compatibleStyles: ["luxury"],
    bestUsedFor: ["portrait", "establishing", "detail"],
    cameraBehavior: "Elegant tracking shot continues underneath.",
    visualEffectBehavior: "Color-matched, evenly-paced cross-fade.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "low",
    affinities: ["subtle"],
  },
  {
    id: "shadowToLight",
    displayName: "Shadow To Light",
    description: "The frame moves from shadow into light as the cut happens, implying refinement and reveal.",
    durationRange: [2.0, 3.4],
    intensity: 2,
    compatibleStyles: ["luxury"],
    bestUsedFor: ["detail", "portrait"],
    cameraBehavior: "Premium light movement tracks the shadow-to-light arc.",
    visualEffectBehavior: "Exposure ramp from underexposed to key-lit.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["subtle"],
  },
  {
    id: "premiumReveal",
    displayName: "Premium Reveal",
    description: "A slow, product-launch-style reveal of the next shot from soft blur into full clarity.",
    durationRange: [2.2, 3.5],
    intensity: 2,
    compatibleStyles: ["luxury"],
    bestUsedFor: ["detail", "establishing", "closeUp"],
    cameraBehavior: "Slow detail reveal sharpening into product framing.",
    visualEffectBehavior: "Defocus-to-focus reveal with soft bloom.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "medium",
    affinities: ["subtle"],
  },
  {
    id: "slowGradientFade",
    displayName: "Slow Gradient Fade",
    description: "A directional gradient fades the frame out and the next shot in, with no hard edge.",
    durationRange: [2.5, 4.0],
    intensity: 1,
    compatibleStyles: ["luxury"],
    bestUsedFor: ["establishing", "detail"],
    cameraBehavior: "Low-speed controlled camera holds through the gradient.",
    visualEffectBehavior: "Linear gradient opacity fade.",
    easing: "linear",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "low",
    affinities: ["subtle"],
  },
];

// ---------------------------------------------------------------------------
// Shared fades — smooth, readable, cinematic-feeling transitions available to
// the styles that need "breathing room" between shots: Viral (so a fast edit
// can still pause and let a shot register instead of feeling chaotic), and
// Travel / Cinematic / Luxury (whose whole identity is a smooth, premium
// flow rather than hard cuts). Every one of these renders as a real xfade
// cross-blend in the exported video (see `xfadeMapping.ts`) — never just a
// metadata label with no visible effect.
// ---------------------------------------------------------------------------
const sharedFadeTransitions: TransitionDefinition[] = [
  {
    id: "fadeIn",
    displayName: "Fade In",
    description: "The next shot gently fades in from a soft blend of the previous frame — no hard edge, no jarring pop.",
    durationRange: [0.6, 1.5],
    intensity: 2,
    compatibleStyles: ["viral", "travel", "cinematic", "luxury"],
    bestUsedFor: ["establishing", "landscape", "detail"],
    cameraBehavior: "Camera holds steady through the blend so the incoming shot reads clearly.",
    visualEffectBehavior: "Opacity ramp from the outgoing frame into the incoming one.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "low",
    affinities: ["subtle", "flow"],
  },
  {
    id: "fadeOut",
    displayName: "Fade Out",
    description: "The current shot gently fades out before the next one settles in — gives the viewer a beat to process what they just saw.",
    durationRange: [0.6, 1.5],
    intensity: 2,
    compatibleStyles: ["viral", "travel", "cinematic", "luxury"],
    bestUsedFor: ["establishing", "landscape", "detail"],
    cameraBehavior: "Camera holds steady as the shot dims out.",
    visualEffectBehavior: "Opacity ramp down toward black before the next frame appears.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "low",
    affinities: ["subtle", "flow"],
  },
  {
    id: "crossFade",
    displayName: "Cross Fade",
    description: "A clean, even dissolve between the two shots — the single most readable, least jarring transition in the whole system.",
    durationRange: [0.7, 1.6],
    intensity: 2,
    compatibleStyles: ["viral", "travel", "cinematic", "luxury", "adventure", "sport"],
    bestUsedFor: ["establishing", "landscape", "action", "detail"],
    cameraBehavior: "Neutral — works underneath any camera move.",
    visualEffectBehavior: "Even cross-dissolve blend with no directional bias.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "low",
    affinities: ["subtle", "flow"],
  },
  {
    id: "softFade",
    displayName: "Soft Fade",
    description: "A slightly slower, extra-gentle fade for moments that need to breathe — the calmest transition available outside Luxury's own palette.",
    durationRange: [0.9, 1.5],
    intensity: 1,
    compatibleStyles: ["viral", "travel", "cinematic", "luxury"],
    bestUsedFor: ["establishing", "landscape", "detail"],
    cameraBehavior: "Slow, settled camera holds through the blend.",
    visualEffectBehavior: "Low-contrast opacity blend, softer falloff than a standard cross fade.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "low",
    affinities: ["subtle"],
  },
  {
    id: "fadeThroughBlack",
    displayName: "Fade Through Black",
    description: "The shot fades all the way to black before the next one rises out of it — a stronger separation beat for a bigger tonal shift.",
    durationRange: [0.8, 1.5],
    intensity: 3,
    compatibleStyles: ["viral", "travel", "cinematic", "luxury"],
    bestUsedFor: ["establishing", "action", "detail"],
    cameraBehavior: "Camera settles fully before the black beat.",
    visualEffectBehavior: "Fade to full black, hold briefly, fade up into the next shot.",
    easing: "easeInOut",
    requiresTerrainContext: false,
    requiresBeatSync: false,
    performanceCost: "low",
    affinities: ["subtle", "story"],
  },
];

/** Flat lookup of every transition definition, keyed by id — the single source of truth `TransitionSelector`/`TransitionEngine` read from. */
export const TRANSITION_PRESETS: Record<TransitionId, TransitionDefinition> = [
  ...adventureTransitions,
  ...viralTransitions,
  ...travelTransitions,
  ...sportTransitions,
  ...cinematicTransitions,
  ...luxuryTransitions,
  ...sharedFadeTransitions,
].reduce(
  (acc, def) => {
    acc[def.id] = def;
    return acc;
  },
  {} as Record<TransitionId, TransitionDefinition>
);

export const ALL_TRANSITION_IDS: TransitionId[] = Object.keys(TRANSITION_PRESETS) as TransitionId[];
